### ISSUE TITLE
Correcciones

### ISSUE THREAD

**Issue by AlvaroMartinFernandez** [4GeeksAcademy/ericvega-instagram#1]
Buen uso del flex  y de la distribuccion del contenido te pongo un par de problemas que necesito que corrijas-

- [ ] Utiliza fontAwesome para los iconos es importante ya que los utilizaras mas adelante, te tendras que registrar para poder hacer uso de ellos (https://fontawesome.com/) importante que los iconos ocupen todos el mismo tamaño y esten alineados y centrados.

<img width="290" alt="image" src="https://github.com/user-attachments/assets/28e04cd0-d734-472c-914e-7e08e47c23fd">
<img width="299" alt="image" src="https://github.com/user-attachments/assets/1acce03d-e75f-44e4-88d2-4cad436f3fbb">

Por el resto esta perfecto.

**Comment by EricVega** [comment]
Disculpad por todo lo que ha pasado, hoy me estoy poniendo a resolver todos los errores que tengo en las entregas de proyectos,  acabo de corregir lo que me has pedido,

Un saludo, gracias.

**Comment by AlvaroMartinFernandez** [comment]
Esta correcto para aprobar el primer proyecto pero cuidado 
![image](https://github.com/user-attachments/assets/bd706a8c-7b51-4fa9-8539-5aa3a0b95038)
 el icono de compartir deberia estar centrado y abajo dejas mucho espacio en blanco
